In [1]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])
print(data.shape)
meanteem=np.mean(data,axis=1)
meanteem
high_temp= data[data > 28]
high_temp

normalized = (data - data.min()) / (data.max() - data.min())


normalized_rounded = np.round(normalized, 2)

print(normalized_rounded)

(4, 5)
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
